language: python
python:
  - "3.6"

services: postgresql
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

# Allow the sudo command
sudo: true

env:
  global:
  - DJANGO_SETTINGS_MODULE="django_project.settings.tests"
  - PIP_USE_MIRRORS=true
  - BUILD_ON_TRAVIS=true
  matrix:
    - DB=postgresql

#commands to install dependencies
before_install:
  - sudo apt-get install -qq gdal-bin
  - sudo apt-get install -qq postgresql-10-postgis-2.4
  - sudo apt-get install -qq postgis  

install:
  - pip install -q -r requirements.txt
  
before_script:
  - createdb im2webapp
  - cd im2webapp
  - python manage.py migrate


#command to run the test suite
script:
  - ./check_migrations.sh
  - ./check_locales.sh
  - flake8 .
  - python manage.py test
