version: '3.7'

services:
  db:
    image: postgres:10
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    command: python /home/italo/imagens-medicas-2/im2webapp/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/italo/imagens-medicas-2/
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres_data:
